


export enum SECTIONS {
    HERO = "HERO",
    FEATURED = "FEATURED",
    CTAONE = "CTAONE",
    CTATWO = "CTATWO",
    CTATHREE = "CTATHREE",
    CTAFOUR = "CTAFOUR",
    CTAFIVE = "CTAFIVE",
    CTASIX = "CTASIX",
    CTASEVEN = "CTASEVEN",
    CTAEIGHT = "CTAEIGHT",
    ABOUTUS = "ABOUTUS",
    RESULTS = "RESULTS",
    BRANCHES = "BRANCHES",
    CONTACTUS = "CONTACTUS",
    COMPANYDEVELOPMENT = "COMPANYDEVELOPMENT",
    MANAGEMENTMARKETING = "MANAGEMENTMARKETING",
    STABILITYSECURITY = "STABILITYSECURITY",
}